name: "Run pre-commit hooks"

on:
  push:
    branches: [main, dev, 'feature/**']
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: Install pre-commit dependencies
        run: pip install -r requirements-dev.txt

      - name: Run all hooks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  tests:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
